#!/bin/bash

[ "$1" == "-h" -o "$1" == "" ] && {
echo "M12/Econotag Flasher: usage ./flash_m12 (m12|econnotag) firmware.bin"
exit 1
}

[ "$1" != "" -a "$2" != "" ] && {

  LIBMC1322X=../libmc1322x
  TOOLS=${LIBMC1322X}/tools
  FLASHER=${LIBMC1322X}/tests/flasher_m12.bin
  BBMC=${LIBMC1322X}/tools/ftditools/bbmc
  #FIRMWARE=../ofldongle/ofldongle_m12.bin
  FIRMWARE=$2

  if [ "$1" == "m12" ] 	
  then
    FLASHER=${LIBMC1322X}/tests/flasher_m12.bin
  elif [ "$1" == "econotag" ] 
  then
    FLASHER=${LIBMC1322X}/tests/flasher_redbee-econotag.bin
  else
    echo "!  Target can be m12 or econotag"
    exit 0; 
  fi 


  ${TOOLS}/mc1322x-load.pl -t /dev/ttyUSB1  -f ${FLASHER} -s ${FIRMWARE}  -c "sudo ${BBMC} -l redbee-econotag erase; sudo ${BBMC}  -l redbee-econotag reset" -b 200
}
